### ISSUE TITLE
数据集？

### ISSUE THREAD

**Issue by chenqi13814529300** [NVlabs/InstantSplat#12]
是否可以直接使用colmap的数据，我看您的数据集中有深度图啊，深度图这个东西不太容易获得，尤其是准确的深度图

**Comment by kairunwen** [comment]
Poses from colmap cannot be used directly because they are not aligned with the poses from dust3r. (see fig below)
![image](https://github.com/user-attachments/assets/cd393e91-26dc-4a1b-8f1b-511ef8082e09)

The depthmaps in data link are used for comparison method, i will clean it and update link.

**Comment by Master-cai** [comment]
@kairunwen Hi, I want to ask how to visualize the camera pose like this ?

**Comment by kairunwen** [comment]
> ? Hi, I want to ask how to visualize the camera pose like this 

https://github.com/demul/extrinsic2pyramid
