### ISSUE TITLE
How can I use my own data to train and test?

### ISSUE THREAD

**Issue by gwxxx** [NVlabs/InstantSplat#16]

**Comment by Yenhongxuan** [comment]
I have the same question. How can I train and evaluate on dataset like ScanNet? Also, how to prepare the ground truth pose in ScanNet so that we use the ground truth pose for evaluating pose estimation instead of using poses from COLMAP?

**Comment by kairunwen** [comment]
> How can I use my own data to train and test?

Hi, we slightly modified the FSGS [script](https://github.com/VITA-Group/FSGS/blob/main/tools/colmap_360.py) to obtain the ground truth pose and other relevant data. Feel free to modify it for your own dataset.

**Comment by Yenhongxuan** [comment]
> > How can I use my own data to train and test?
> 
> Hi, we slightly modified the FSGS [script](https://github.com/VITA-Group/FSGS/blob/main/tools/colmap_360.py) to obtain the ground truth pose and other relevant data. Feel free to modify it for your own dataset.

Sorry, the script provided seems to retrieve poses and other data from the original COLMAP data if I don't misunderstand. However, it appears that only RGB images and images.bin (Used to evaluate the pose estimation) are needed. How could I generate the poses using ground truth poses from ScanNet but not retrieve them from COLMAP data?

**Comment by kairunwen** [comment]
> Sorry, the script provided seems to retrieve poses and other data from the original COLMAP data if I don't misunderstand. However, it appears that only RGB images and images.bin (Used to evaluate the pose estimation) are needed. How could I generate the poses using ground truth poses from ScanNet but not retrieve them from COLMAP data?
Please correct me if there are any mistakes.

You can write a script to read ScanNet data and save it in COLMAP format.
Reference：
(1) [https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py](url)
(2) [https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/colmap_loader.py](url)
