### ISSUE TITLE
The rendering results seem strange

### ISSUE THREAD

**Issue by murmurelo111** [NVlabs/InstantSplat#17]
![image](https://github.com/user-attachments/assets/b94605ea-dfea-4277-9717-de9f775970df)

I ran ‘bash scripts/run_train_eval.sh’ and got this, Could you help me fix it?

**Comment by murmurelo111** [comment]
`GT_POSE_PATH=${DATA_ROOT_DIR}/Tanks_colmap/${SCENE}/24_views`
Also, the Tanks_colmap path in this code doesn't seem to exist

**Comment by kairunwen** [comment]
> GT_POSE_PATH=${DATA_ROOT_DIR}/Tanks_colmap/${SCENE}/24_views
Also, the Tanks_colmap path in this code doesn't seem to exist

`GT_POSE_PATH=${DATA_ROOT_DIR}/Tanks_colmap/${SCENE}/24_views` --> `GT_POSE_PATH=${DATA_ROOT_DIR}/Tanks/${SCENE}/24_views`

**Comment by murmurelo111** [comment]
Thanks for your reply!
