### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by eloquentarduino** [NVlabs/InstantSplat#19]
Tried replicating your work.
When running `python train_joint.py ...`, I get the following error:

```
ImportError: cannot import name '_C' from partially initialized module 'diff_gaussian_rasterization' 
(most likely due to a circular import) (/InstantSplat/submodules/diff-gaussian-rasterization/diff_gaussian_rasterization/__init__.py)
```

Any hint?

**Comment by kairunwen** [comment]
Hi @eloquentarduino, you might consider building a new container using our Docker images and then re-running the code.
