### ISSUE TITLE
Reevaluate License 

### ISSUE THREAD

**Issue by jburns-spectralreality** [NVlabs/InstantSplat#20]
DUSt3R which underlies InstantSplat is [CC-NC-4.0](https://github.com/naver/dust3r/blob/main/LICENSE), which isn't compatible with Apache 2.0. Please reevaluate the license in order to avoid confusion.

**Comment by zhiwenfan** [comment]
Hi, we’ve added more details about the license. The new code in InstantSplat is released under the Apache License. However, we utilize other libraries, such as DUSt3R and 3D Gaussian Splatting, for initialization and additional functionalities. Please ensure you follow their respective license terms and restrictions when using them.

Thanks for your feedback!
