### ISSUE TITLE
No pose found 

### ISSUE THREAD

**Issue by resurgo97** [NVlabs/InstantSplat#21]
Hi, I ran `bash scripts/run_train_infer.sh` without changing anything, and got this error:

========= santorini: Render interpolated pose & output video =========
Looking for config file in ./output/infer/sora/santorini/3_views_1000Iter_1xPoseLR/cfg_args
Config file found: ./output/infer/sora/santorini/3_views_1000Iter_1xPoseLR/cfg_args
Rendering ./output/infer/sora/santorini/3_views_1000Iter_1xPoseLR/
Traceback (most recent call last):
  File "/mnt/nas2/ksy/InstantSplat/./render_by_interp.py", line 143, in <module>
    render_sets(
  File "/mnt/nas2/ksy/InstantSplat/./render_by_interp.py", line 98, in render_sets
    save_interpolate_pose(dataset.model_path, iteration, args.n_views)
  File "/mnt/nas2/ksy/InstantSplat/./render_by_interp.py", line 33, in save_interpolate_pose
    org_pose = np.load(model_path + f"pose/pose_{iter}.npy")
  File "/opt/conda/lib/python3.10/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './output/infer/sora/santorini/3_views_1000Iter_1xPoseLR/pose/pose_1000.npy'

Can anyone help me with this error?

Thanks!

**Comment by Tracy-coder** [comment]
Same problem~

**Comment by vamWu** [comment]
I think you just need to change the "DATA_ROOT_DIR and GPU_ID....." to the same path as your local.

**Comment by tlxhlll** [comment]
I also found this error, so what should GPU_ID be changed?

**Comment by kairunwen** [comment]
@resurgo97, Hi, The code has been refactored and updated. You can try running `bash scripts/run_infer.sh` again.
