### ISSUE TITLE
Question about optimizing camera poses

### ISSUE THREAD

**Issue by makise-kurisu-004** [NVlabs/InstantSplat#22]
Hello,

Thanks for the great work! I have tried the published code successfully and I am amazed at the reconstruction quality.

However, there is still a question for me that how can we optimize the camera poses using photometric loss with the original gaussian-rasterization? Because, as far as I know, the vanilla rasterizator doesn't support back propagation of camera poses gradients. I print the intermediate results of camera poses, and they do have gradients and being updated. I did not find relevant description in the paper. Is there any relevant processing for this in the code?

Again, appreciate for the fancy and wonderful work!

**Comment by kairunwen** [comment]
Hi @makise-kurisu-004, thanks for your interest! Please see issue #4.

**Comment by makise-kurisu-004** [comment]
Hi ,

Thanks for replying and I got it! It is a really smart way to bypass the problem of optimizing camera poses directly. I have no more questions.
