### ISSUE TITLE
Datasets ?????????????????

### ISSUE THREAD

**Issue by Z-zachary** [NVlabs/InstantSplat#24]
Thank you very much for your work!!!

The dataset provided in the link doesn't work, it's missing a lot.
For example, there is no training dataset and no testing dataset. pts_3dgs_all.npy also not

**Comment by kairunwen** [comment]
Hi @Z-zachary, thanks for your interest!
We put all images in the link, you can see this [issue #11](https://github.com/NVlabs/InstantSplat/issues/11#issuecomment-2311524435) to split training set and testing set, and then get pts_3dgs_all.npy [here](https://github.com/NVlabs/InstantSplat/blob/main/coarse_init_eval.py#L108).

**Comment by Z-zachary** [comment]
> Hi @Z-zachary, thanks for your interest! We put all images in the link, you can see this [issue #11](https://github.com/NVlabs/InstantSplat/issues/11#issuecomment-2311524435) to split training set and testing set, and then get pts_3dgs_all.npy [here](https://github.com/NVlabs/InstantSplat/blob/main/coarse_init_eval.py#L108).

Thanks for your reply. 
I cannot find the files from the datasets which is downloaded from the link you improved(Data preparation (Our pre-processed data: [link](https://drive.google.com/file/d/1Z17tIgufz7-eZ-W0md_jUlxq89CD1e5s/view))).

There are only eval datasets in the link,i can not get such as pts_3dgs_all.npy files.
