### ISSUE TITLE
Camera parameters for rendering images

### ISSUE THREAD

**Issue by Z-zachary** [NVlabs/InstantSplat#27]
Thank you very, very much for your work, really the best work in years.

I would like to know what the camera parameters are for the rendered 275 photos.Where are the camera parameters. Do these 275 photos contain the previous training inputs?

How are the camera parameters for these 275 photos determined and can I set them myself?

**Comment by Z-zachary** [comment]
Where are the camera parameters

**Comment by Z-zachary** [comment]
There seems to be a problem with the external parameters of the rendered image, each camera is looking right down, they are in the right position, but not in the right direction, as if the rotation matrix is useless
![微信图片_20241012140030](https://github.com/user-attachments/assets/08cfe8ed-c11f-4c95-bf99-f94dd55b7d51)

**Comment by kairunwen** [comment]
@Z-zachary, Hi, it looks like there's an issue with how you're visualizing the camera parameters. You could try using this repo: https://github.com/demul/extrinsic2pyramid.
