### ISSUE TITLE
Schedule to release support for 2D-GS?

### ISSUE THREAD

**Issue by zzhang2816** [NVlabs/InstantSplat#30]
Thanks for the impressive work. Is there any schedule to release support for 2D-GS?

**Comment by kairunwen** [comment]
Hi @zzhang2816 , Thanks for your interest! We will release this within a week.

**Comment by ddenglina** [comment]
> Hi @zzhang2816 , Thanks for your interest! We will release this within a week.
The release version still not support for 2D-GS.

**Comment by ddenglina** [comment]
> Hi @zzhang2816 , Thanks for your interest! We will release this within a week.

em....The  new released version still not support 2D-GS

**Comment by kairunwen** [comment]
@zzhang2816 @ddenglina, Hi, apologies for the delay in the release. The InstantSplat-2DGS code has been updated and is available here: https://github.com/NVlabs/InstantSplat/tree/instantsplat-2dgs. Thank you so much for your patience! You can run the script `bash scripts/run_infer.sh` to generate the mesh shown below. Feel free to reach out if you need any assistance :D

![image](https://github.com/user-attachments/assets/b24cae72-46d4-47c8-85ac-69cb53088f2c)

**Comment by zzhang2816** [comment]
Thank you for updating the InstantSplat-2DGS code and providing clear instructions. I appreciate your effort and support—looking forward to exploring it!
