### ISSUE TITLE
Multi view reconstruction？

### ISSUE THREAD

**Issue by chenqi13814529300** [NVlabs/InstantSplat#31]
I have found that these studies often involve reconstructing a few images, but in reality, hundreds or thousands of images are used to reconstruct a closed scene, rather than a 180 degree perspective. May I ask if there will be support for a large number of image inputs for scene reconstruction in the future?

**Comment by WangHaoran16** [comment]
I also have the same question

**Comment by kairunwen** [comment]
@chenqi13814529300, Thanks for your interest!

To run InstantSplat on scenes with a large number of images (e.g., 100+), it's advisable to process the images in smaller chunks to better manage memory usage.

**Suggested Approach:**
- Set the `window_size` to 24 images per chunk during Global Geometry Initialization, with overlapping windows across chunks for better alignment.
- After processing each chunk, align the next set of 12 images as a new chunk using Points Registration.

**Reference Function:** Points Registration (https://github.com/NVlabs/InstantSplat/blob/main/utils/sfm_utils.py#L101-L104)

**Example Workflow:**
- **Chunk 1:** Images 1–24
- **Chunk 2:** Images 13–36

**Steps:**
- Perform Points Registration between the Pointmaps of images 13–24 in Chunk 1 and images 13–24 in Chunk 2.
- Retrieve the scale, rotation (R), and translation (T).
- Apply the obtained scale, R, and T to the Pointmaps and Poses of images 25–36 in Chunk 2, aligning the next 12 images.

This approach ensures efficient memory management while achieving proper alignment across large image sets. Additionally, you can adjust the scene graph parameters to further speed up the Global Geometry Initialization process. (please refer to https://github.com/NVlabs/InstantSplat/issues/10#issuecomment-2311540472).
