### ISSUE TITLE
AssertionError: Number of images (4) in the folder (/root/tf-logs/InstantSplat/data/sora/santorini/3_views/images) is not equal to 3

### ISSUE THREAD

**Issue by cjcjcj666** [NVlabs/InstantSplat#32]
Traceback (most recent call last):
  File "/root/tf-logs/InstantSplat/./coarse_init_infer.py", line 57, in <module>
    assert len(train_img_list)==n_views, f"Number of images ({len(train_img_list)}) in the folder ({img_folder_path}) is not equal to {n_views}"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Number of images (4) in the folder (/root/tf-logs/InstantSplat/data/sora/santorini/3_views/images) is not equal to 3

**Comment by kairunwen** [comment]
@cjcjcj666, Hi, you might want to check the number of pictures in the folder `assets/sora/Santorini/images`. It’s possible that you accidentally copied an extra one, which is why there are now four pictures.
