### ISSUE TITLE
where can i get the pose result?

### ISSUE THREAD

**Issue by smart4654154** [NVlabs/InstantSplat#36]
you let the network predict the camera poses for all input images while also learning the varying scale factors across different scenes.

so where  can I get the predicted pose result?
thank you.
What I mean is, where can the predicted pose be located and output it?
I want to generate results similar to colmap matching, such as bin or blender JSON files
So I can use other algorithms for comparative testing. Because other algorithms require poses

**Comment by kairunwen** [comment]
Hi, thanks for your interest! You can find the corresponding pose results at:
-  Initial training pose: `<source_path>/sparse_${n_views}/0/images.bin` or `<source_path>/sparse_${n_views}/0/images.txt`

-  Initial testing pose: `<source_path>/sparse_${n_views}/1/images.bin` or `<source_path>/sparse_${n_views}/1/images.txt`
- Optimized training pose: `<model_path>/pose/ours_${train_iterations}/pose_optimized.npy`
