### ISSUE TITLE
Is the paper on the Arxiv website the latest version？

### ISSUE THREAD

**Issue by Lionetxx** [NVlabs/InstantSplat#38]
I really hope to receive your reply! I am currently reading your paper
Is the paper on the Arxiv website the latest version? Why is the pipeline in it different from the pipeline on the project website?
![image](https://github.com/user-attachments/assets/6a64311b-7d38-4555-a8eb-9e25de5d6eb9)
![image](https://github.com/user-attachments/assets/3dd1d13c-dbb9-4cbf-affd-286a383df15c)

**Comment by kairunwen** [comment]
Hi @Lionetxx, Thanks for your interest! We will update the paper on Arxiv within three days.
