### ISSUE TITLE
Where can I find equation number 6 in your code?

### ISSUE THREAD

**Issue by RoyAmoyal** [NVlabs/InstantSplat#4]
Hey, thanks for sharing the code for your cool work!

I can't find the code section related to equation number 6, where you jointly optimize the gaussians together with the camera parameters. (3.3. Joint Optimization for Alignment)

I can only find the original training of Gaussian Splatting in train_joint.py that optimizes the gaussians like in the original 3DGS, but not the camera poses. (I can't find the difference in the cuda backward section too)

![image](https://github.com/user-attachments/assets/c11f5d3b-a2b3-451b-9463-22536dd79a45)

thanks!

**Comment by murmurelo111** [comment]
![image](https://github.com/user-attachments/assets/d5b3699c-062c-4912-b6a5-5a54ebfcd512)
train_joint.py

**Comment by RoyAmoyal** [comment]
> ![image](https://private-user-images.githubusercontent.com/129838471/357369928-d5b3699c-062c-4912-b6a5-5a54ebfcd512.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzIwODcsIm5iZiI6MTcyMzYzMTc4NywicGF0aCI6Ii8xMjk4Mzg0NzEvMzU3MzY5OTI4LWQ1YjM2OTljLTA2MmMtNDkxMi1iNmE1LTVhNTRlYmZjZDUxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMDM2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjIwNWZmM2Q0ZDhjNDBhNmQxOTZiZjlkNjFkMWIxNzUyY2I5YzkxZGJiZGNhODI2ZDc1NjM3MDNiODJjM2JkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k3usGUJNrHGIBX7VIytQRxo3nU081lFdB75MXaMoRaY) train_joint.py

It's the exactly same Loss as the original Gaussian Splatting. I don't see where they optimize the camera poses (extrinsic's of the cameras, that T's in their equation) along with the 3DGS. That's requires additional code in the CUDA and in the loss. 

I can also verify that using an example where the DUST3R its not providing perfectly camera poses, so you can see a little bit miss align points clouds from different directions, and the Instant Splat doesn't deal with it. 

Right now it seems they took DUST3R -> got poses and points clouds for the scene -> fed the original 3DGS with the DUST3R's poses and they init the gaussians with the DUST3R's point clouds.

**Comment by kairunwen** [comment]
https://github.com/NVlabs/InstantSplat/blob/main/scene/gaussian_model.py#L237
https://github.com/NVlabs/InstantSplat/blob/main/gaussian_renderer/__init__.py

**Comment by RoyAmoyal** [comment]
> https://github.com/NVlabs/InstantSplat/blob/main/scene/gaussian_model.py#L237 https://github.com/NVlabs/InstantSplat/blob/main/gaussian_renderer/__init__.py

That's it! 

Thanks!!
