### ISSUE TITLE
Is it possible to save  points3D.bin or points3D.txt in save_points3D?

### ISSUE THREAD

**Issue by a11enL** [NVlabs/InstantSplat#44]
Is it possible to save  points3D.bin or points3D.txt in save_points3D (sfm_utils.py)?

Then we can try to test and compare more Gaussian splatting training solutions.

**Comment by kairunwen** [comment]
Hi, the relevant functions for saving point clouds can be found here:
- https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py#L358-L387.
- https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py#L390-L425.

**Comment by QingyangLiu** [comment]
> Hi, the relevant functions for saving point clouds can be found here:
> 
>     * https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py#L358-L387.
> 
>     * https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py#L390-L425.

That's for reading in .bin and .txt.  Pretty sure the original question was how to save the pts3D values as points3D.bin or points3D.txt.  Now sure why this thread was closed considering how the original question wasn't exactly answered I do not believe.

**Comment by jwd222** [comment]
> > Hi, the relevant functions for saving point clouds can be found here:
> > ```
> > * https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py#L358-L387.
> > 
> > * https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py#L390-L425.
> > ```
> 
> That's for reading in .bin and .txt. Pretty sure the original question was how to save the pts3D values as points3D.bin or points3D.txt. Now sure why this thread was closed considering how the original question wasn't exactly answered I do not believe.

I think the line numbers are incorrect in the original reply, but the functions are available in the mentioned file from this line onwards:
[https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py#L428](https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py#L428)
