### ISSUE TITLE
Simple KNN Submodule

### ISSUE THREAD

**Issue by IshanArya** [NVlabs/InstantSplat#5]
Hello,

Can you please add the code for the simple-knn submodule? It is not linked anywhere.

**Comment by IshanArya** [comment]
Nvm, it's available here: https://gitlab.inria.fr/bkerbl/simple-knn.git

**Comment by ojh6404** [comment]
FYI.
for who wants to compile simple-knn with higher than cuda 12.5, you need to add
'#include<cfloat>'
to simple_knn.cu.
