### ISSUE TITLE
Can I do dense reconstruction using this method?

### ISSUE THREAD

**Issue by LaFeuilleMorte** [NVlabs/InstantSplat#6]
Thanks for your brilliant work! Apparently this method is focused on sparse view synthesis. But I tried several datasets but found the results were not met with my expectation. So I considered using more images, Can this method also work in dense views? Also, I noticed that the dust3r pipeline significantly slowed down when using too many views (For ex. 300 views) as the image pairs generated will be n^2 where n is the image num. Looking forward to your reply

**Comment by kairunwen** [comment]
@LaFeuilleMorte , Thanks for your interest!

To run InstantSplat on scenes with a large number of images (e.g., 100+), it's advisable to process the images in smaller chunks to better manage memory usage.

**Suggested Approach:**
- Set the `window_size` to 24 images per chunk during Global Geometry Initialization, with overlapping windows across chunks for better alignment.
- After processing each chunk, align the next set of 12 images as a new chunk using Points Registration.

**Reference Function:** Points Registration (https://github.com/NVlabs/InstantSplat/blob/main/utils/sfm_utils.py#L101-L104)

**Example Workflow:**
- **Chunk 1:** Images 1–24
- **Chunk 2:** Images 13–36

**Steps:**
- Perform Points Registration between the Pointmaps of images 13–24 in Chunk 1 and images 13–24 in Chunk 2.
- Retrieve the scale, rotation (R), and translation (T).
- Apply the obtained scale, R, and T to the Pointmaps and Poses of images 25–36 in Chunk 2, aligning the next 12 images.

This approach ensures efficient memory management while achieving proper alignment across large image sets. Additionally, you can adjust the scene graph parameters to further speed up the Global Geometry Initialization process. (please refer to https://github.com/NVlabs/InstantSplat/issues/10#issuecomment-2311540472).
