### ISSUE TITLE
Questions About Downsampling

### ISSUE THREAD

**Issue by Ysc-shark** [NVlabs/InstantSplat#7]
What a great work! It achieves very fast and accurate sparse view reconstruction and novel view synthesis.

I am very interested in your work and have a few questions about downsampling:

- Your module "Adaptive Dense Surface Point Initialization" is very ingenious. I would like to know, regarding the reconstruction using the point cloud of dust3r as Gaussian initialization, do you think the point downsampling method is the key to success?

- You reported that the performance of the confidence-based global downsampling method was not good. Have you tried using other simple downsampling methods, such as Open3d's random_down_sample and voxel_down_sample? How much worse are they compared to your method?

- From your ablation experiments, it can be seen that the partitioning parameter K has some impact on performance. For scenes with different characteristics and sizes, how to choose the optimal K? Do you have any suggestions?

Thank you so much!

**Comment by iYuqinL** [comment]
I am also interested in point cloud sampling, but I seem to can't find the point sampling code corresponding to what mentioned in the paper. 
<img width="704" alt="image" src="https://github.com/user-attachments/assets/90170de5-8caf-40e8-90a5-5bda3c773854">

May you give me some tips about this?

**Comment by Master-cai** [comment]
They has not released the downsampling code, indicated in the `TODO` of the readme.

**Comment by Livioni** [comment]
> I am also interested in point cloud sampling, but I seem to can't find the point sampling code corresponding to what mentioned in the paper. <img alt="image" width="704" src="https://private-user-images.githubusercontent.com/25427848/356073018-90170de5-8caf-40e8-90a5-5bda3c773854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NzcwNzUsIm5iZiI6MTcyMzg3Njc3NSwicGF0aCI6Ii8yNTQyNzg0OC8zNTYwNzMwMTgtOTAxNzBkZTUtOGNhZi00MGU4LTkwYTUtNWJkYTNjNzczODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDA2MzkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMzI2MGVkMTRjODUxMmNjMGZlZDA4MDk4ZjFiNzFiYTBhY2YzOTA4Yjg3ZTBhMTA4ZDdhNjNlNzc0ZWRlY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OqTp25s7qJm2riHavTsTY50_IL54yd6xRm_5ZrEKN2I">
> 
> May you give me some tips about this?

I want to know what the $c_v$ in the equations in the second line represents, is it color or confidence score?

**Comment by kairunwen** [comment]
> > I am also interested in point cloud sampling, but I seem to can't find the point sampling code corresponding to what mentioned in the paper. <img alt="image" width="704" src="https://private-user-images.githubusercontent.com/25427848/356073018-90170de5-8caf-40e8-90a5-5bda3c773854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NzcwNzUsIm5iZiI6MTcyMzg3Njc3NSwicGF0aCI6Ii8yNTQyNzg0OC8zNTYwNzMwMTgtOTAxNzBkZTUtOGNhZi00MGU4LTkwYTUtNWJkYTNjNzczODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDA2MzkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMzI2MGVkMTRjODUxMmNjMGZlZDA4MDk4ZjFiNzFiYTBhY2YzOTA4Yjg3ZTBhMTA4ZDdhNjNlNzc0ZWRlY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OqTp25s7qJm2riHavTsTY50_IL54yd6xRm_5ZrEKN2I">
> > May you give me some tips about this?
> 
> I want to know what the c v in the equations in the second line represents, is it color or confidence score?

confidence score

**Comment by kk6398** [comment]
> They has not released the downsampling code, indicated in the `TODO` of the readme.

Is the photometric error code open source? I have reviewed your code and found that in train_joint.py. After performing differentiability operations on pose, only L1 loss and ssim loss same as 3dgs are still used in the loss function part

**Comment by gotoHappy** [comment]
![image](https://github.com/user-attachments/assets/1cd8d66a-8df6-4a47-bde3-0bfdfe2ca3b8)
I am confused as to why K is taken like this

**Comment by Livioni** [comment]
> ![image](https://private-user-images.githubusercontent.com/114345873/361149634-1cd8d66a-8df6-4a47-bde3-0bfdfe2ca3b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MTE1MzIsIm5iZiI6MTcyNDUxMTIzMiwicGF0aCI6Ii8xMTQzNDU4NzMvMzYxMTQ5NjM0LTFjZDhkNjZhLThkZjYtNGE0Ny1iZGUzLTBiZmRmZTJjYTNiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQxNDUzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDI3ODQ1MzZmODJkMTUwN2E3NWRlYzNmMGJiOGFjMzdmNjA5NTNkMDgwZjdjOGMwNjE5MDBjYTlhNDlmY2I4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kPSGUSWrL8CINoU-GRbhpJEDnSFFPyx1eN-I8Hf7uik) I am confused as to why K is taken like this

I also think that this equation is a little bit unclear in the paper, because the they said "and $K$ is the point number in the $V_j$." 
Doesn't K come from this equation？

**Comment by 7yzx** [comment]
Is the released code in `train_joint.py` the same as the original 3dgs, except for the addition of camera pose optimization?

**Comment by hebing-sjtu** [comment]
Using the Tank, Family, n_view = 9 example, the scene has 676k GS points. How many GS points remain after downsampling? Do the downsampling ratios stay constant across different sequences and n_views?

**Comment by zhiwenfan** [comment]
We have updated the code with the preprint accordingly. Thanks for your patience!
